server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:inventory;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS inventory
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: inventory
        multiTenancy: SCHEMA

  flyway:
    locations: classpath:db/migration
    schemas: inventory

logging:
  level:
    root: INFO
